AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway and Lambda functions for Deal Discovery App'

Parameters:
  Environment:
    Type: String
    Default: dev
  PhotoBucket:
    Type: String
  ProcessingQueueUrl:
    Type: String
  ProcessingQueueArn:
    Type: String
  DatabaseEndpoint:
    Type: String
  LambdaExecutionRoleArn:
    Type: String

Resources:
  # Security Group for Lambda functions
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !ImportValue 
        Fn::Sub: 'deal-discovery-database-${Environment}-VPC'
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # Photo Upload Lambda
  PhotoUploadFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'photo-upload-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async () => ({ statusCode: 200, body: 'Placeholder' });
      Role: !Ref LambdaExecutionRoleArn
      Environment:
        Variables:
          PHOTO_BUCKET: !Ref PhotoBucket
          PROCESSING_QUEUE_URL: !Ref ProcessingQueueUrl
      Timeout: 30

  # Deals API Lambda
  DealsApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'deals-api-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async () => ({ statusCode: 200, body: 'Placeholder' });
      Role: !Ref LambdaExecutionRoleArn
      Environment:
        Variables:
          DB_HOST: !Ref DatabaseEndpoint
          DB_PORT: '5432'
          DB_NAME: dealdb
          DB_USER: dealadmin
          DB_PASSWORD: TempPassword123!
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !ImportValue 
            Fn::Sub: 'deal-discovery-database-${Environment}-PrivateSubnet1'
          - !ImportValue 
            Fn::Sub: 'deal-discovery-database-${Environment}-PrivateSubnet2'

  # Deal Processor Lambda (Python)
  DealProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'deal-processor-${Environment}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
      Role: !Ref LambdaExecutionRoleArn
      Environment:
        Variables:
          DB_HOST: !Ref DatabaseEndpoint
          DB_PORT: '5432'
          DB_NAME: dealdb
          DB_USER: dealadmin
          DB_PASSWORD: TempPassword123!
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !ImportValue 
            Fn::Sub: 'deal-discovery-database-${Environment}-PrivateSubnet1'
          - !ImportValue 
            Fn::Sub: 'deal-discovery-database-${Environment}-PrivateSubnet2'

  # SQS Event Source for Deal Processor
  DealProcessorEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref ProcessingQueueArn
      FunctionName: !Ref DealProcessorFunction
      BatchSize: 10

  # API Gateway
  DealApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'deal-api-${Environment}'
      Description: Deal Discovery API

  # API Gateway Resource
  PhotoResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DealApi
      ParentId: !GetAtt DealApi.RootResourceId
      PathPart: photo

  # API Gateway Resource for deals
  DealsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DealApi
      ParentId: !GetAtt DealApi.RootResourceId
      PathPart: deals

  # API Gateway Resource for individual deal
  DealByIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DealApi
      ParentId: !Ref DealsResource
      PathPart: '{id}'

  # API Gateway Resource for geocode
  GeocodeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DealApi
      ParentId: !GetAtt DealApi.RootResourceId
      PathPart: geocode

  # API Gateway Method for GET /deals
  DealsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref DealsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DealsApiFunction.Arn}/invocations'

  # API Gateway Method for GET /deals/{id}
  DealByIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref DealByIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DealsApiFunction.Arn}/invocations'

  # API Gateway Method for POST /geocode
  GeocodePostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref GeocodeResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PhotoUploadFunction.Arn}/invocations'

  # CORS OPTIONS method for geocode endpoint
  GeocodeOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref GeocodeResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Lambda Permissions for API Gateway
  DealsApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DealsApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DealApi}/*/*'

  # CORS OPTIONS method for photo endpoint
  PhotoOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref PhotoResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Method
  PhotoUploadMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DealApi
      ResourceId: !Ref PhotoResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PhotoUploadFunction.Arn}/invocations'

  # Lambda Permission for API Gateway
  PhotoUploadPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PhotoUploadFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DealApi}/*/POST/photo'

  # Lambda Permission for Geocode endpoint
  GeocodePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PhotoUploadFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DealApi}/*/POST/geocode'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - PhotoUploadMethod
      - PhotoOptionsMethod
      - DealsGetMethod
      - DealByIdGetMethod
      - GeocodePostMethod
      - GeocodeOptionsMethod
    Properties:
      RestApiId: !Ref DealApi
      StageName: !Ref Environment

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${DealApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  PhotoUploadFunctionArn:
    Description: Photo Upload Lambda ARN
    Value: !GetAtt PhotoUploadFunction.Arn

  LambdaSecurityGroupId:
    Description: Security Group ID for Lambda functions
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-LambdaSecurityGroupId'
    Export:
      Name: !Sub '${AWS::StackName}-PhotoUploadFunction'
