AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deal Discovery App Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  # S3 Bucket for photo storage
  PhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # SQS Queue for async processing
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'deal-processing-${Environment}'
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: DealAppPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub 'arn:aws:s3:::${PhotoBucket}/*'
                  - !Sub 'arn:aws:s3:::${PhotoBucket}'
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ProcessingQueue.Arn
              - Effect: Allow
                Action:
                  - rekognition:DetectText
                Resource: '*'
              - Effect: Allow
                Action:
                  - geo:SearchPlaceIndexForText
                  - geo:SearchPlaceIndexForPosition
                Resource: '*'

Outputs:
  PhotoBucketName:
    Description: Name of the S3 bucket for photos
    Value: !Ref PhotoBucket
    Export:
      Name: !Sub '${AWS::StackName}-PhotoBucket'

  ProcessingQueueUrl:
    Description: URL of the SQS processing queue
    Value: !Ref ProcessingQueue
    Export:
      Name: !Sub '${AWS::StackName}-ProcessingQueue'

  ProcessingQueueArn:
    Description: ARN of the SQS processing queue
    Value: !GetAtt ProcessingQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProcessingQueueArn'

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRole'
